name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v1

      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 21.0.0.java11

      - name: Setup Clojure CLI
        uses: DeLaGuardo/setup-clojure@master
        with:
          # To use Clojure CLI 1.10.1.561 based on tools.deps
          cli: '1.10.2.796'

      - name: Test clojure present
        run: clojure -Sdescribe

      - name: Make staging directory
        run: mkdir staging

      - name: Make target dir
        run: mkdir -p target/classes

      - name: Clojure Build
        run: clojure -e "(binding [*compile-path* \"target/classes\"] (compile 'thomasa.hello))"

      - name: Gluon Build
        run: mvn client:build client:package
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}

      - name: Copy native client to staging
        run: cp -r target/client/x86_64-windows/clj-hellofx staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
